### ISSUE TITLE
component prop types should come from 'prop-types' package

### ISSUE THREAD

**Issue by brooksbecton** [netguru/atom-react-es6-snippets#13]
If you are using React v15.5 or greater then you are supposed to start getting your prop types from the standalone package 'prop-types' based on the [React Typechecking Docs](https://reactjs.org/docs/typechecking-with-proptypes.html)

```javascript 
import PropTypes from 'prop-types';
```
Most of the snippets still import PropTypes from React which is depreciating. [Example](https://github.com/netguru/atom-react-es6-snippets/blob/master/snippets/React%20(ES6).cson#L20)

I would be glad to do a PR for this, but adding in the correct import would assume that someone is using React v15.5 and have the 'prop-types' package installed. Not a huge deal, but just a small problem I see if the change is made.

**Comment by zedd45** [comment]
I suppose one could fork this repo.  

I'm not sure it's still maintained, as It hasn't seen a change in 2 years.  I'm encountering the same issue.

**Comment by brooksbecton** [comment]
I've made one here! https://atom.io/packages/basic-react-snippets

I just made it so it may take a minute for it to start showing up through atom!
