### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by oscar-g** [netguru/atom-react-es6-snippets#7]
I am using this set of snippets in a project where I have the airbnb eslint rules. What is the best way to make these snippets conform to those style rules?

Should I fork my own and manually install them in atom?

Or, are you willing to merge a PR that uses airbnb code style?

Thanks so much!

**Comment by Szeliga** [comment]
We would like to conform with airbnb's code style, so if you have any fixes available, then submit a PR with them :)
